[env:t5-47]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git
    miniz
    tinyxml2

[env:native]
platform = native
build_flags = 
    -std=c++11
    -D NATIVE_TESTING
# Hardware libraries (like epd_driver) will be stubbed or wrapped in SDL for this environment
