[platformio]
boards_dir = boards

[env:t5-47-s3]
platform = espressif32
board = T5-ePaper-S3
framework = arduino
upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOOP_STACK_SIZE=32768
    -DCORE_DEBUG_LEVEL=3
    -DLILYGO_T5_EPD47_S3
    -DMZ_MALLOC=malloc
    -DMZ_FREE=free
    -DMZ_REALLOC=realloc

lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson@^7.0.0

[env:native]
platform = native
build_flags = 
    -std=c++11
    -D NATIVE_TESTING
    -D HAS_SDL
    -I/usr/include/SDL2
    -lSDL2
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
